### ISSUE TITLE
Build Error (Missing POMs for utils.io:utils.io and utils.xml:utils.xml)

### ISSUE THREAD

**Issue by rsynnest** [mpi2/exportlibrary#1]
Hi guys, I am getting a maven build error which seems to be stemming from missing POM files for `org.mousephenotype.dcc.utils.io:utils.io:jar:1.0.0` and `org.mousephenotype.dcc.utils.xml:utils.xml:jar:1.0.0`
I may be missing something obvious but I am not a Java developer, just trying to build the newest version of the validation tool.
Here is the relevant section of output returned by `mvn -e clean install` :

```
[INFO] Building exportlibrary.xsdvalidation 1.3.3
[INFO] ------------------------------------------------------------------------
Downloading: http://repository.codehaus.org/org/codehaus/mojo/failsafe-maven-plugin/2.4.3-alpha-1/failsafe-maven-plugin-2.4.3-alpha-1.pom
Downloading: http://repo1.maven.org/maven2/org/codehaus/mojo/failsafe-maven-plugin/2.4.3-alpha-1/failsafe-maven-plugin-2.4.3-alpha-1.pom
Downloaded: http://repo1.maven.org/maven2/org/codehaus/mojo/failsafe-maven-plugin/2.4.3-alpha-1/failsafe-maven-plugin-2.4.3-alpha-1.pom (8 KB at 331.2 KB/sec)
Downloading: http://repository.codehaus.org/org/codehaus/mojo/mojo-parent/21/mojo-parent-21.pom
Downloading: http://repo1.maven.org/maven2/org/codehaus/mojo/mojo-parent/21/mojo-parent-21.pom
Downloaded: http://repo1.maven.org/maven2/org/codehaus/mojo/mojo-parent/21/mojo-parent-21.pom (19 KB at 757.4 KB/sec)
Downloading: http://repository.codehaus.org/org/codehaus/mojo/failsafe-maven-plugin/2.4.3-alpha-1/failsafe-maven-plugin-2.4.3-alpha-1.jar
Downloading: http://repo1.maven.org/maven2/org/codehaus/mojo/failsafe-maven-plugin/2.4.3-alpha-1/failsafe-maven-plugin-2.4.3-alpha-1.jar
Downloaded: http://repo1.maven.org/maven2/org/codehaus/mojo/failsafe-maven-plugin/2.4.3-alpha-1/failsafe-maven-plugin-2.4.3-alpha-1.jar (39 KB at 1360.6 KB/sec)
Downloading: http://repository.codehaus.org/com/google/code/maven-replacer-plugin/replacer/1.5.0/replacer-1.5.0.pom
Downloading: http://repo1.maven.org/maven2/com/google/code/maven-replacer-plugin/replacer/1.5.0/replacer-1.5.0.pom
Downloaded: http://repo1.maven.org/maven2/com/google/code/maven-replacer-plugin/replacer/1.5.0/replacer-1.5.0.pom (6 KB at 214.5 KB/sec)
Downloading: http://repository.codehaus.org/com/google/code/maven-replacer-plugin/replacer/1.5.0/replacer-1.5.0.jar
Downloading: http://repo1.maven.org/maven2/com/google/code/maven-replacer-plugin/replacer/1.5.0/replacer-1.5.0.jar
Downloaded: http://repo1.maven.org/maven2/com/google/code/maven-replacer-plugin/replacer/1.5.0/replacer-1.5.0.jar (29 KB at 959.4 KB/sec)
Downloading: http://repository.codehaus.org/org/apache/maven/plugins/maven-surefire-plugin/2.12/maven-surefire-plugin-2.12.pom
Downloading: http://repo1.maven.org/maven2/org/apache/maven/plugins/maven-surefire-plugin/2.12/maven-surefire-plugin-2.12.pom
Downloaded: http://repo1.maven.org/maven2/org/apache/maven/plugins/maven-surefire-plugin/2.12/maven-surefire-plugin-2.12.pom (10 KB at 289.5 KB/sec)
Downloading: http://repository.codehaus.org/org/apache/maven/surefire/surefire/2.12/surefire-2.12.pom
Downloading: http://repo1.maven.org/maven2/org/apache/maven/surefire/surefire/2.12/surefire-2.12.pom
Downloaded: http://repo1.maven.org/maven2/org/apache/maven/surefire/surefire/2.12/surefire-2.12.pom (11 KB at 369.6 KB/sec)
Downloading: http://repository.codehaus.org/org/apache/maven/plugins/maven-surefire-plugin/2.12/maven-surefire-plugin-2.12.jar
Downloading: http://repo1.maven.org/maven2/org/apache/maven/plugins/maven-surefire-plugin/2.12/maven-surefire-plugin-2.12.jar
Downloaded: http://repo1.maven.org/maven2/org/apache/maven/plugins/maven-surefire-plugin/2.12/maven-surefire-plugin-2.12.jar (31 KB at 1205.5 KB/sec)
Downloading: http://repo1.maven.org/maven2/org/mousephenotype/dcc/utils/io/utils.io/1.0.0/utils.io-1.0.0.pom
Downloading: https://repository.jboss.org/nexus/content/groups/public-jboss/org/mousephenotype/dcc/utils/io/utils.io/1.0.0/utils.io-1.0.0.pom
Downloading: https://repo.maven.apache.org/maven2/org/mousephenotype/dcc/utils/io/utils.io/1.0.0/utils.io-1.0.0.pom
[WARNING] The POM for org.mousephenotype.dcc.utils.io:utils.io:jar:1.0.0 is missing, no dependency information available
Downloading: http://repo1.maven.org/maven2/org/mousephenotype/dcc/utils/xml/utils.xml/1.0.0/utils.xml-1.0.0.pom
Downloading: https://repository.jboss.org/nexus/content/groups/public-jboss/org/mousephenotype/dcc/utils/xml/utils.xml/1.0.0/utils.xml-1.0.0.pom
Downloading: https://repo.maven.apache.org/maven2/org/mousephenotype/dcc/utils/xml/utils.xml/1.0.0/utils.xml-1.0.0.pom
[WARNING] The POM for org.mousephenotype.dcc.utils.xml:utils.xml:jar:1.0.0 is missing, no dependency information available
Downloading: http://repo1.maven.org/maven2/org/mousephenotype/dcc/utils/xml/utils.xml/1.0.0/utils.xml-1.0.0.jar
Downloading: http://repo1.maven.org/maven2/org/mousephenotype/dcc/utils/io/utils.io/1.0.0/utils.io-1.0.0.jar
Downloading: https://repository.jboss.org/nexus/content/groups/public-jboss/org/mousephenotype/dcc/utils/io/utils.io/1.0.0/utils.io-1.0.0.jar
Downloading: https://repository.jboss.org/nexus/content/groups/public-jboss/org/mousephenotype/dcc/utils/xml/utils.xml/1.0.0/utils.xml-1.0.0.jar
Downloading: https://repo.maven.apache.org/maven2/org/mousephenotype/dcc/utils/xml/utils.xml/1.0.0/utils.xml-1.0.0.jar
Downloading: https://repo.maven.apache.org/maven2/org/mousephenotype/dcc/utils/io/utils.io/1.0.0/utils.io-1.0.0.jar
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] exportlibrary-parent ............................... SUCCESS [ 11.535 s]
[INFO] exportlibrary.datastructure ........................ SUCCESS [ 25.887 s]
[INFO] exportlibrary.xsdvalidation ........................ FAILURE [  1.284 s]
[INFO] exportlibrary.exportcommunication .................. SKIPPED
[INFO] exportlibrary.exporterworker ....................... SKIPPED
[INFO] exportlibrary.xmlinstantiation ..................... SKIPPED
[INFO] exportlibrary.xmlserialization ..................... SKIPPED
[INFO] exportlibrary.xmlvalidationdatastructure ........... SKIPPED
[INFO] exportlibrary.xmlvalidationremoteclients ........... SKIPPED
[INFO] exportlibrary.xmlvalidationresourcescollection ..... SKIPPED
[INFO] exportlibrary.validationRemover .................... SKIPPED
[INFO] exportlibrary.traverser ............................ SKIPPED
[INFO] exportlibrary.fullTraverser ........................ SKIPPED
[INFO] exportlibrary.xmlvalidation ........................ SKIPPED
[INFO] exportlibrary.impressexamplesgeneration ............ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 40.085 s
[INFO] Finished at: 2017-02-28T22:39:57+00:00
[INFO] Final Memory: 45M/538M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project exportlibrary.xsdvalidation: Could not resolve dependencies for project org.mousephenotype.dcc.exportlibrary.xsdvalidation:exportlibrary.xsdvalidation:jar:1.3.3: The following artifacts could not be resolved: org.mousephenotype.dcc.utils.io:utils.io:jar:1.0.0, org.mousephenotype.dcc.utils.xml:utils.xml:jar:1.0.0: Could not find artifact org.mousephenotype.dcc.utils.io:utils.io:jar:1.0.0 in maven2 (http://repo1.maven.org/maven2) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project exportlibrary.xsdvalidation: Could not resolve dependencies for project org.mousephenotype.dcc.exportlibrary.xsdvalidation:exportlibrary.xsdvalidation:jar:1.3.3: The following artifacts could not be resolved: org.mousephenotype.dcc.utils.io:utils.io:jar:1.0.0, org.mousephenotype.dcc.utils.xml:utils.xml:jar:1.0.0: Could not find artifact org.mousephenotype.dcc.utils.io:utils.io:jar:1.0.0 in maven2 (http://repo1.maven.org/maven2)
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:221)
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies(LifecycleDependencyResolver.java:127)
	at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:245)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:199)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project org.mousephenotype.dcc.exportlibrary.xsdvalidation:exportlibrary.xsdvalidation:jar:1.3.3: The following artifacts could not be resolved: org.mousephenotype.dcc.utils.io:utils.io:jar:1.0.0, org.mousephenotype.dcc.utils.xml:utils.xml:jar:1.0.0: Could not find artifact org.mousephenotype.dcc.utils.io:utils.io:jar:1.0.0 in maven2 (http://repo1.maven.org/maven2)
	at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:211)
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:195)
	... 23 more
Caused by: org.eclipse.aether.resolution.DependencyResolutionException: The following artifacts could not be resolved: org.mousephenotype.dcc.utils.io:utils.io:jar:1.0.0, org.mousephenotype.dcc.utils.xml:utils.xml:jar:1.0.0: Could not find artifact org.mousephenotype.dcc.utils.io:utils.io:jar:1.0.0 in maven2 (http://repo1.maven.org/maven2)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:384)
	at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:205)
	... 24 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: The following artifacts could not be resolved: org.mousephenotype.dcc.utils.io:utils.io:jar:1.0.0, org.mousephenotype.dcc.utils.xml:utils.xml:jar:1.0.0: Could not find artifact org.mousephenotype.dcc.utils.io:utils.io:jar:1.0.0 in maven2 (http://repo1.maven.org/maven2)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:367)
	... 25 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact org.mousephenotype.dcc.utils.io:utils.io:jar:1.0.0 in maven2 (http://repo1.maven.org/maven2)
	at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:39)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:355)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :exportlibrary.xsdvalidation
```

**Comment by rsynnest** [comment]
Note for future reference:
After you get this failure you need to build the [utils](https://github.com/mpi2/utils) package, which is used during the `exportlibrary` build process.
Once `utils` is installed then you can continue to build the `exportlibrary` package.
The [utils](https://github.com/mpi2/utils) package also has a build error which can be fixed by editing `utils.xml/pom.xml` and `utils.persistence/pom.xml` to match the version of `exportlibrary.datastructure`  in `https://github.com/mpi2/exportlibrary` (this repo) (in my case I changed the version from `3.7` to `3.8.1` in both files).

After successfully building the `utils` package I was able to continue building the `exportlibrary` package, but the build failed again at `exportlibrary.xmlinstantiation`, likely due to another mpi2 dependency.
I only needed the `xsdvalidation` JAR, which was built successfully before the failure, so I stopped troubleshooting at this point.
